run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - unconvert
    - goconst
    - bodyclose

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - shadow
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true
  
  gosec:
    excludes:
      - G104
      - G304
  
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
